# Only my changes
# Format: [shortcut.<ID>] where <ID> is displayed in the UI as the first column ID

[Control%2BPrint.20]
Comment=screen shot region direct
Enabled=true
Exec=screengrab, -rmn

[Shift%2BPrint.33]
Comment=screen shot full direct
Enabled=true
Exec=scrot, -f, screen-%Y-%m-%d-%H-%M-%S.png

[Alt%2BPrint.44]
Comment=screen shot active window
Enabled=true
Exec=scrot, -u, -b, -f, screen-%Y-%m-%d-%H-%M-%S.png

[Meta%2BPrint.45]
Comment=screen shot window under mouse
Enabled=true
Exec=scrot, -s, -b, -f, screen-%Y-%m-%d-%H-%M-%S.png


###############################################################################
# Not sure if these are defaults or custom
###############################################################################
[XF86AudioLowerVolume.34]
Comment=Decrease sound volume
Enabled=true
path=/panel/volume/down

[XF86AudioMute.35]
Comment=Mute/unmute sound volume
Enabled=true
path=/panel/volume/mute

[XF86AudioRaiseVolume.36]
Comment=Increase sound volume
Enabled=true
path=/panel/volume/up

[XF86Display.37]
Comment=Launch Monitor
Enabled=true
Exec=lxqt-config-monitor

[XF86Eject.38]
Comment=Eject removable media
Enabled=true
path=/panel/mount/eject

[XF86MonBrightnessDown.39]
Comment=☀ ↓
Enabled=true
Exec=lxqt-config-brightness, -d

[XF86MonBrightnessUp.40]
Comment=☀ ↑
Enabled=true
Exec=lxqt-config-brightness, -i

[XF86PowerOff.41]
Comment=Power off key action
Enabled=true
path=/powermanager/keypoweroff

[XF86Sleep.42]
Comment=Hibernate key action
Enabled=true
path=/powermanager/keyhibernate

[XF86Suspend.43]
Comment=Suspend key action
Enabled=true
path=/powermanager/keysuspend

