################################################################################
# [20230422] Chromium 112.0.5615.165 Arch Linux
################################################################################
--incognito
--force-device-scale-factor=1.6
--disk-cache-size=1
--disable-software-rasterizer
--enable-gpu-rasterization
--enable-oop-rasterization
--canvas-oop-rasterization
--enable-gpu-compositing
--enable-zero-copy
--enable-accelerated-2d-canvas
--enable-accelerated-video-decode
--enable-accelerated-mjpeg-decode
--enable-raw-draw
--use-vulkan
--enable-features=VaapiVideoDecoder,VaapiIgnoreDriverChecks,CanvasOopRasterization,PlatformHEVCDecoderSupport,Vulkan,DefaultANGLEVulkan,VulkanFromANGLE
--disable-features=UseChromeOSDirectVideoDecoder

################################################################################
# [20260502] Newer tests, CPU util still cannot beat active settings.
################################################################################
## https://www.reddit.com/r/linux/comments/17o4zg7/comment/lwhngnp/
##--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL,UseChromeOSDirectVideoDecoder
#--enable-native-gpu-memory-buffers
#--ozone-platform-hint=auto
###
#--ignore-gpu-blocklist
#--enable-zero-copy
##--enable-features=AcceleratedVideoDecodeLinuxGL
#--enable-features=VaapiVideoDecoder,VaapiVideoEncoder,VaapiVideoDecodeLinuxGL,UseChromeOSDirectVideoDecoder,AcceleratedVideoDecodeLinuxGL

# TESTING: https://www.youtube.com/watch?v=VRah-zYboFw


################################################################################
# [20230422] Deprecated. Kept for "FYI historical context" only.
################################################################################
#--ignore-gpu-blocklist
#--disable-gpu-driver-bug-workarounds
#--disable-features=UseChromeOSDirectVideoDecoder,DefaultPassthroughCommandDecode
#--auto-open-devtools-for-tabs

# [202304xx] This no longer working, and will cause hw-accel disabled!
# For XWayland. For Xorg, use desktop. See: https://bbs.archlinux.org/viewtopic.php?pid=2081197#p2081197
#--use-gl=egl
#--use-gl=desktop
