#requires -version 5.1

# HAHA: Generated by Codex (Pro mode). Gemini or Perplexity generates in-effective script.

<#
.SYNOPSIS
Moves each newly managed komorebi window to the monitor containing the mouse pointer.

.DESCRIPTION
This script hosts the Windows named pipe that komorebi writes subscription events to.
It tracks window handles so that Show/Uncloak events for existing windows are ignored,
and it continuously drains the pipe on a background .NET thread so commands issued by
this script cannot deadlock komorebi's notification writer.

Run one instance only. Stop it with Ctrl+C.
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$Komorebic = "komorebic.exe",

    [Parameter()]
    [ValidateRange(250, 10000)]
    [int]$FocusTimeoutMilliseconds = 1500,

    [Parameter()]
    [ValidateRange(250, 10000)]
    [int]$MoveVerificationTimeoutMilliseconds = 1500
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not ("KomorebiMouseSpawner.PipeMessagePump" -as [type])) {
    Add-Type -TypeDefinition @'
using System;
using System.Collections.Concurrent;
using System.IO;
using System.IO.Pipes;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;

namespace KomorebiMouseSpawner
{
    public static class NativeMethods
    {
        [StructLayout(LayoutKind.Sequential)]
        public struct POINT
        {
            public int X;
            public int Y;
        }

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool GetPhysicalCursorPos(out POINT point);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool GetCursorPos(out POINT point);

        [DllImport("user32.dll")]
        public static extern IntPtr GetForegroundWindow();

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool SetForegroundWindow(IntPtr hwnd);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool BringWindowToTop(IntPtr hwnd);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool ShowWindowAsync(IntPtr hwnd, int command);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool IsIconic(IntPtr hwnd);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool IsZoomed(IntPtr hwnd);

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool IsWindow(IntPtr hwnd);

        [DllImport("user32.dll")]
        public static extern uint GetWindowThreadProcessId(IntPtr hwnd, IntPtr processId);

        [DllImport("kernel32.dll")]
        public static extern uint GetCurrentThreadId();

        [DllImport("user32.dll")]
        [return: MarshalAs(UnmanagedType.Bool)]
        public static extern bool AttachThreadInput(uint attachThread, uint attachToThread, bool attach);
    }

    public sealed class PipeMessage
    {
        public string Line { get; private set; }
        public int CursorX { get; private set; }
        public int CursorY { get; private set; }
        public long ForegroundHwnd { get; private set; }

        public PipeMessage(string line, int cursorX, int cursorY, long foregroundHwnd)
        {
            Line = line;
            CursorX = cursorX;
            CursorY = cursorY;
            ForegroundHwnd = foregroundHwnd;
        }
    }

    public sealed class PipeMessagePump : IDisposable
    {
        private readonly NamedPipeServerStream pipe;
        private readonly Thread thread;
        private volatile bool stopping;

        public BlockingCollection<PipeMessage> Messages { get; private set; }
        public ManualResetEventSlim Connected { get; private set; }
        public Exception Error { get; private set; }

        public PipeMessagePump(NamedPipeServerStream pipe)
        {
            this.pipe = pipe;
            Messages = new BlockingCollection<PipeMessage>(new ConcurrentQueue<PipeMessage>());
            Connected = new ManualResetEventSlim(false);
            thread = new Thread(Pump);
            thread.IsBackground = true;
            thread.Name = "komorebi mouse-spawner pipe reader";
        }

        public void Start()
        {
            thread.Start();
        }

        private void Pump()
        {
            try
            {
                pipe.WaitForConnection();
                Connected.Set();

                using (var reader = new StreamReader(
                    pipe,
                    new UTF8Encoding(false),
                    true,
                    65536,
                    true))
                {
                    string line;
                    while (!stopping && (line = reader.ReadLine()) != null)
                    {
                        NativeMethods.POINT point;
                        if (!NativeMethods.GetPhysicalCursorPos(out point))
                        {
                            NativeMethods.GetCursorPos(out point);
                        }

                        long foreground = NativeMethods.GetForegroundWindow().ToInt64();
                        Messages.Add(new PipeMessage(line, point.X, point.Y, foreground));
                    }
                }
            }
            catch (ObjectDisposedException)
            {
                // Expected during shutdown.
            }
            catch (IOException ex)
            {
                if (!stopping)
                {
                    Error = ex;
                }
            }
            catch (Exception ex)
            {
                if (!stopping)
                {
                    Error = ex;
                }
            }
            finally
            {
                Connected.Set();
                Messages.CompleteAdding();
            }
        }

        public void Dispose()
        {
            stopping = true;

            try { pipe.Dispose(); } catch { }

            if (thread.IsAlive && Thread.CurrentThread != thread)
            {
                thread.Join(1000);
            }

            Connected.Dispose();
            Messages.Dispose();
        }
    }
}
'@
}

function Get-RingElements {
    param(
        [Parameter()]
        [AllowNull()]
        [object]$Ring
    )

    if ($null -eq $Ring) {
        return
    }

    $elementsProperty = $Ring.PSObject.Properties["elements"]
    if ($null -eq $elementsProperty -or $null -eq $elementsProperty.Value) {
        return
    }

    foreach ($element in @($elementsProperty.Value)) {
        Write-Output $element
    }
}

function Get-FocusedRingElement {
    param(
        [Parameter()]
        [AllowNull()]
        [object]$Ring
    )

    $elements = @(Get-RingElements -Ring $Ring)
    if ($elements.Count -eq 0) {
        return $null
    }

    $focusedIndex = 0
    $focusedProperty = $Ring.PSObject.Properties["focused"]
    if ($null -ne $focusedProperty -and $null -ne $focusedProperty.Value) {
        $focusedIndex = [int]$focusedProperty.Value
    }

    if ($focusedIndex -lt 0 -or $focusedIndex -ge $elements.Count) {
        return $null
    }

    return $elements[$focusedIndex]
}

function Add-WindowLocation {
    param(
        [Parameter(Mandatory)]
        [hashtable]$Map,

        [Parameter()]
        [AllowNull()]
        [object]$Window,

        [Parameter(Mandatory)]
        [int]$MonitorIndex,

        [Parameter(Mandatory)]
        [int]$WorkspaceIndex,

        [Parameter(Mandatory)]
        [string]$Kind,

        [Parameter()]
        [int]$ContainerIndex = -1,

        [Parameter()]
        [int]$ContainerWindowCount = 1
    )

    if ($null -eq $Window) {
        return
    }

    $hwndProperty = $Window.PSObject.Properties["hwnd"]
    if ($null -eq $hwndProperty -or $null -eq $hwndProperty.Value) {
        return
    }

    $hwnd = [Int64]$hwndProperty.Value
    if ($hwnd -eq 0) {
        return
    }

    $Map[[string]$hwnd] = [pscustomobject]@{
        Hwnd                 = $hwnd
        MonitorIndex         = $MonitorIndex
        WorkspaceIndex       = $WorkspaceIndex
        Kind                 = $Kind
        ContainerIndex       = $ContainerIndex
        ContainerWindowCount = $ContainerWindowCount
    }
}

function Get-WindowLocationMap {
    param(
        [Parameter(Mandatory)]
        [object]$State
    )

    $map = @{}
    $monitors = @(Get-RingElements -Ring $State.monitors)

    for ($monitorIndex = 0; $monitorIndex -lt $monitors.Count; $monitorIndex++) {
        $monitor = $monitors[$monitorIndex]
        $workspaces = @(Get-RingElements -Ring $monitor.workspaces)

        for ($workspaceIndex = 0; $workspaceIndex -lt $workspaces.Count; $workspaceIndex++) {
            $workspace = $workspaces[$workspaceIndex]
            $containers = @(Get-RingElements -Ring $workspace.containers)

            for ($containerIndex = 0; $containerIndex -lt $containers.Count; $containerIndex++) {
                $container = $containers[$containerIndex]
                $windows = @(Get-RingElements -Ring $container.windows)

                foreach ($window in $windows) {
                    Add-WindowLocation `
                        -Map $map `
                        -Window $window `
                        -MonitorIndex $monitorIndex `
                        -WorkspaceIndex $workspaceIndex `
                        -Kind "Tiling" `
                        -ContainerIndex $containerIndex `
                        -ContainerWindowCount $windows.Count
                }
            }

            $floatingProperty = $workspace.PSObject.Properties["floating_windows"]
            if ($null -ne $floatingProperty -and $null -ne $floatingProperty.Value) {
                foreach ($window in @(Get-RingElements -Ring $floatingProperty.Value)) {
                    Add-WindowLocation `
                        -Map $map `
                        -Window $window `
                        -MonitorIndex $monitorIndex `
                        -WorkspaceIndex $workspaceIndex `
                        -Kind "Floating"
                }
            }

            $monocleProperty = $workspace.PSObject.Properties["monocle_container"]
            if ($null -ne $monocleProperty -and $null -ne $monocleProperty.Value) {
                $monocleWindows = @(Get-RingElements -Ring $monocleProperty.Value.windows)
                foreach ($window in $monocleWindows) {
                    Add-WindowLocation `
                        -Map $map `
                        -Window $window `
                        -MonitorIndex $monitorIndex `
                        -WorkspaceIndex $workspaceIndex `
                        -Kind "Monocle" `
                        -ContainerWindowCount $monocleWindows.Count
                }
            }

            $maximizedProperty = $workspace.PSObject.Properties["maximized_window"]
            if ($null -ne $maximizedProperty -and $null -ne $maximizedProperty.Value) {
                Add-WindowLocation `
                    -Map $map `
                    -Window $maximizedProperty.Value `
                    -MonitorIndex $monitorIndex `
                    -WorkspaceIndex $workspaceIndex `
                    -Kind "Maximized"
            }
        }
    }

    return $map
}

function Get-NotificationEventType {
    param(
        [Parameter(Mandatory)]
        [object]$Notification
    )

    $eventProperty = $Notification.PSObject.Properties["event"]
    if ($null -eq $eventProperty -or $null -eq $eventProperty.Value) {
        return $null
    }

    $typeProperty = $eventProperty.Value.PSObject.Properties["type"]
    if ($null -eq $typeProperty -or $null -eq $typeProperty.Value) {
        return $null
    }

    return [string]$typeProperty.Value
}

function Get-NotificationEventHwnd {
    param(
        [Parameter(Mandatory)]
        [object]$Notification
    )

    $eventProperty = $Notification.PSObject.Properties["event"]
    if ($null -eq $eventProperty -or $null -eq $eventProperty.Value) {
        return $null
    }

    $contentProperty = $eventProperty.Value.PSObject.Properties["content"]
    if ($null -eq $contentProperty -or $null -eq $contentProperty.Value) {
        return $null
    }

    $items = @($contentProperty.Value)
    for ($index = $items.Count - 1; $index -ge 0; $index--) {
        $item = $items[$index]
        if ($null -eq $item) {
            continue
        }

        $hwndProperty = $item.PSObject.Properties["hwnd"]
        if ($null -ne $hwndProperty -and $null -ne $hwndProperty.Value) {
            return [Int64]$hwndProperty.Value
        }
    }

    return $null
}

function Get-KomorebiMonitorRectangle {
    param(
        [Parameter(Mandatory)]
        [object]$Monitor
    )

    $rect = $null
    $rectKind = $null

    foreach ($propertyName in @("size", "screen_rect", "work_area_size")) {
        $property = $Monitor.PSObject.Properties[$propertyName]
        if ($null -ne $property -and $null -ne $property.Value) {
            $rect = $property.Value
            $rectKind = $propertyName
            break
        }
    }

    if ($null -eq $rect) {
        return $null
    }

    $left = [Int64]$rect.left
    $top = [Int64]$rect.top

    $widthProperty = $rect.PSObject.Properties["width"]
    $heightProperty = $rect.PSObject.Properties["height"]

    if ($null -ne $widthProperty -and $null -ne $heightProperty) {
        $width = [Int64]$widthProperty.Value
        $height = [Int64]$heightProperty.Value
    }
    elseif ($rectKind -eq "size" -or $rectKind -eq "work_area_size") {
        # komorebi's Rect stores width in right and height in bottom.
        $width = [Int64]$rect.right
        $height = [Int64]$rect.bottom
    }
    else {
        # Older state versions used screen_rect; its right/bottom values were also dimensions.
        $width = [Int64]$rect.right
        $height = [Int64]$rect.bottom
    }

    if ($width -le 0 -or $height -le 0) {
        return $null
    }

    return [pscustomobject]@{
        Left   = $left
        Top    = $top
        Width  = $width
        Height = $height
    }
}

function Get-MonitorIndexAtPoint {
    param(
        [Parameter(Mandatory)]
        [object]$State,

        [Parameter(Mandatory)]
        [int]$X,

        [Parameter(Mandatory)]
        [int]$Y
    )

    $monitors = @(Get-RingElements -Ring $State.monitors)
    if ($monitors.Count -eq 0) {
        throw "komorebi reported no monitors"
    }

    $nearestIndex = 0
    $nearestDistanceSquared = [double]::PositiveInfinity

    for ($index = 0; $index -lt $monitors.Count; $index++) {
        $rectangle = Get-KomorebiMonitorRectangle -Monitor $monitors[$index]
        if ($null -eq $rectangle) {
            continue
        }

        $rightExclusive = $rectangle.Left + $rectangle.Width
        $bottomExclusive = $rectangle.Top + $rectangle.Height

        if (
            $X -ge $rectangle.Left -and
            $X -lt $rightExclusive -and
            $Y -ge $rectangle.Top -and
            $Y -lt $bottomExclusive
        ) {
            return $index
        }

        $dx = 0L
        if ($X -lt $rectangle.Left) {
            $dx = $rectangle.Left - $X
        }
        elseif ($X -ge $rightExclusive) {
            $dx = $X - ($rightExclusive - 1)
        }

        $dy = 0L
        if ($Y -lt $rectangle.Top) {
            $dy = $rectangle.Top - $Y
        }
        elseif ($Y -ge $bottomExclusive) {
            $dy = $Y - ($bottomExclusive - 1)
        }

        $distanceSquared = ([double]$dx * [double]$dx) + ([double]$dy * [double]$dy)
        if ($distanceSquared -lt $nearestDistanceSquared) {
            $nearestDistanceSquared = $distanceSquared
            $nearestIndex = $index
        }
    }

    return $nearestIndex
}

function Invoke-KomorebicCommand {
    param(
        [Parameter(Mandatory)]
        [string[]]$Arguments
    )

    $output = @(& $script:KomorebicPath @Arguments 2>&1)
    $exitCode = $LASTEXITCODE
    $outputText = ($output | ForEach-Object { [string]$_ }) -join [Environment]::NewLine

    return [pscustomobject]@{
        ExitCode = $exitCode
        Output   = $outputText
    }
}

function Get-KomorebiState {
    $result = Invoke-KomorebicCommand -Arguments @("state")
    if ($result.ExitCode -ne 0) {
        throw "komorebic state failed with exit code $($result.ExitCode): $($result.Output)"
    }

    if ([string]::IsNullOrWhiteSpace($result.Output)) {
        throw "komorebic state returned no JSON"
    }

    return ($result.Output | ConvertFrom-Json -ErrorAction Stop)
}

function Test-KomorebiWindowFocused {
    param(
        [Parameter(Mandatory)]
        [object]$State,

        [Parameter(Mandatory)]
        [Int64]$Hwnd
    )

    $monitor = Get-FocusedRingElement -Ring $State.monitors
    if ($null -eq $monitor) {
        return $false
    }

    $workspace = Get-FocusedRingElement -Ring $monitor.workspaces
    if ($null -eq $workspace) {
        return $false
    }

    $maximizedProperty = $workspace.PSObject.Properties["maximized_window"]
    if ($null -ne $maximizedProperty -and $null -ne $maximizedProperty.Value) {
        $maximizedHwndProperty = $maximizedProperty.Value.PSObject.Properties["hwnd"]
        if ($null -ne $maximizedHwndProperty -and [Int64]$maximizedHwndProperty.Value -eq $Hwnd) {
            return $true
        }
    }

    $monocleProperty = $workspace.PSObject.Properties["monocle_container"]
    if ($null -ne $monocleProperty -and $null -ne $monocleProperty.Value) {
        $monocleWindow = Get-FocusedRingElement -Ring $monocleProperty.Value.windows
        if ($null -ne $monocleWindow) {
            $monocleHwndProperty = $monocleWindow.PSObject.Properties["hwnd"]
            if ($null -ne $monocleHwndProperty -and [Int64]$monocleHwndProperty.Value -eq $Hwnd) {
                return $true
            }
        }
    }

    $floatingProperty = $workspace.PSObject.Properties["floating_windows"]
    if ($null -ne $floatingProperty -and $null -ne $floatingProperty.Value) {
        $floatingWindow = Get-FocusedRingElement -Ring $floatingProperty.Value
        if ($null -ne $floatingWindow) {
            $floatingHwndProperty = $floatingWindow.PSObject.Properties["hwnd"]
            if ($null -ne $floatingHwndProperty -and [Int64]$floatingHwndProperty.Value -eq $Hwnd) {
                return $true
            }
        }
    }

    $container = Get-FocusedRingElement -Ring $workspace.containers
    if ($null -eq $container) {
        return $false
    }

    $window = Get-FocusedRingElement -Ring $container.windows
    if ($null -eq $window) {
        return $false
    }

    $hwndProperty = $window.PSObject.Properties["hwnd"]
    return ($null -ne $hwndProperty -and [Int64]$hwndProperty.Value -eq $Hwnd)
}

function Request-ForegroundWindow {
    param(
        [Parameter(Mandatory)]
        [Int64]$Hwnd
    )

    $target = [IntPtr]$Hwnd
    if (-not [KomorebiMouseSpawner.NativeMethods]::IsWindow($target)) {
        return $false
    }

    if ([KomorebiMouseSpawner.NativeMethods]::GetForegroundWindow().ToInt64() -eq $Hwnd) {
        return $true
    }

    if ([KomorebiMouseSpawner.NativeMethods]::IsIconic($target)) {
        # SW_RESTORE
        [void][KomorebiMouseSpawner.NativeMethods]::ShowWindowAsync($target, 9)
    }

    $currentThread = [KomorebiMouseSpawner.NativeMethods]::GetCurrentThreadId()
    $foregroundWindow = [KomorebiMouseSpawner.NativeMethods]::GetForegroundWindow()
    $foregroundThread = 0
    if ($foregroundWindow -ne [IntPtr]::Zero) {
        $foregroundThread = [KomorebiMouseSpawner.NativeMethods]::GetWindowThreadProcessId(
            $foregroundWindow,
            [IntPtr]::Zero
        )
    }

    $targetThread = [KomorebiMouseSpawner.NativeMethods]::GetWindowThreadProcessId(
        $target,
        [IntPtr]::Zero
    )

    $attachedForeground = $false
    $attachedTarget = $false

    try {
        if ($foregroundThread -ne 0 -and $foregroundThread -ne $currentThread) {
            $attachedForeground = [KomorebiMouseSpawner.NativeMethods]::AttachThreadInput(
                $currentThread,
                $foregroundThread,
                $true
            )
        }

        if (
            $targetThread -ne 0 -and
            $targetThread -ne $currentThread -and
            $targetThread -ne $foregroundThread
        ) {
            $attachedTarget = [KomorebiMouseSpawner.NativeMethods]::AttachThreadInput(
                $currentThread,
                $targetThread,
                $true
            )
        }

        [void][KomorebiMouseSpawner.NativeMethods]::BringWindowToTop($target)
        [void][KomorebiMouseSpawner.NativeMethods]::SetForegroundWindow($target)
    }
    finally {
        if ($attachedTarget) {
            [void][KomorebiMouseSpawner.NativeMethods]::AttachThreadInput(
                $currentThread,
                $targetThread,
                $false
            )
        }

        if ($attachedForeground) {
            [void][KomorebiMouseSpawner.NativeMethods]::AttachThreadInput(
                $currentThread,
                $foregroundThread,
                $false
            )
        }
    }

    return ([KomorebiMouseSpawner.NativeMethods]::GetForegroundWindow().ToInt64() -eq $Hwnd)
}

function Wait-ForKomorebiWindowFocus {
    param(
        [Parameter(Mandatory)]
        [Int64]$Hwnd,

        [Parameter(Mandatory)]
        [int]$TimeoutMilliseconds
    )

    $deadline = [DateTime]::UtcNow.AddMilliseconds($TimeoutMilliseconds)
    $nextFocusRequest = [DateTime]::MinValue

    do {
        $now = [DateTime]::UtcNow
        if ($now -ge $nextFocusRequest) {
            [void](Request-ForegroundWindow -Hwnd $Hwnd)
            $nextFocusRequest = $now.AddMilliseconds(250)
        }

        $state = Get-KomorebiState
        $osFocused = (
            [KomorebiMouseSpawner.NativeMethods]::GetForegroundWindow().ToInt64() -eq $Hwnd
        )

        if ($osFocused -and (Test-KomorebiWindowFocused -State $state -Hwnd $Hwnd)) {
            return $state
        }

        Start-Sleep -Milliseconds 35
    }
    while ([DateTime]::UtcNow -lt $deadline)

    return $null
}

function Restore-PreviousForegroundWindow {
    param(
        [Parameter(Mandatory)]
        [Int64]$PreviousForegroundHwnd,

        [Parameter(Mandatory)]
        [Int64]$MovedHwnd
    )

    if (
        $PreviousForegroundHwnd -eq 0 -or
        $PreviousForegroundHwnd -eq $MovedHwnd
    ) {
        return
    }

    $previous = [IntPtr]$PreviousForegroundHwnd
    if ([KomorebiMouseSpawner.NativeMethods]::IsWindow($previous)) {
        [void](Request-ForegroundWindow -Hwnd $PreviousForegroundHwnd)
    }
}

function Move-KomorebiWindowToMonitor {
    param(
        [Parameter(Mandatory)]
        [Int64]$Hwnd,

        [Parameter(Mandatory)]
        [int]$TargetMonitorIndex,

        [Parameter(Mandatory)]
        [object]$NotificationState,

        [Parameter(Mandatory)]
        [Int64]$PreviousForegroundHwnd
    )

    $notificationLocations = Get-WindowLocationMap -State $NotificationState
    $locationKey = [string]$Hwnd
    if (-not $notificationLocations.ContainsKey($locationKey)) {
        return $false
    }

    $notificationLocation = $notificationLocations[$locationKey]
    if ($notificationLocation.MonitorIndex -eq $TargetMonitorIndex) {
        return $true
    }

    $originMonitorIndex = [int]$notificationLocation.MonitorIndex
    $restoreKomorebiMaximize = $false
    $restoreOriginMonocle = $false
    $moved = $false

    try {
        $state = Wait-ForKomorebiWindowFocus `
            -Hwnd $Hwnd `
            -TimeoutMilliseconds $FocusTimeoutMilliseconds

        if ($null -eq $state) {
            Write-Warning "Could not focus new window HWND $Hwnd; it was not moved."
            return $false
        }

        $locations = Get-WindowLocationMap -State $state
        if (-not $locations.ContainsKey($locationKey)) {
            Write-Warning "New window HWND $Hwnd disappeared before it could be moved."
            return $false
        }

        $location = $locations[$locationKey]
        if ($location.MonitorIndex -eq $TargetMonitorIndex) {
            return $true
        }

        if ($location.Kind -eq "Maximized") {
            $toggleMaximize = Invoke-KomorebicCommand -Arguments @("toggle-maximize")
            if ($toggleMaximize.ExitCode -ne 0) {
                Write-Warning "Could not unmaximize HWND ${Hwnd}: $($toggleMaximize.Output)"
                return $false
            }

            $restoreKomorebiMaximize = $true
            $state = Wait-ForKomorebiWindowFocus `
                -Hwnd $Hwnd `
                -TimeoutMilliseconds $FocusTimeoutMilliseconds
        }
        elseif ($location.Kind -eq "Monocle") {
            $toggleMonocle = Invoke-KomorebicCommand -Arguments @("toggle-monocle")
            if ($toggleMonocle.ExitCode -ne 0) {
                Write-Warning "Could not leave monocle mode for HWND ${Hwnd}: $($toggleMonocle.Output)"
                return $false
            }

            $restoreOriginMonocle = $true
            $state = Wait-ForKomorebiWindowFocus `
                -Hwnd $Hwnd `
                -TimeoutMilliseconds $FocusTimeoutMilliseconds
        }

        if ($null -eq $state) {
            Write-Warning "Lost focus on HWND $Hwnd while preparing it for movement."
            return $false
        }

        $locations = Get-WindowLocationMap -State $state
        if (-not $locations.ContainsKey($locationKey)) {
            return $false
        }

        $location = $locations[$locationKey]

        # komorebic move-to-monitor moves a container. If the new window was appended
        # to a stack, unstack it first so existing windows are not moved with it.
        if ($location.Kind -eq "Tiling" -and $location.ContainerWindowCount -gt 1) {
            $unstack = Invoke-KomorebicCommand -Arguments @("unstack")
            if ($unstack.ExitCode -ne 0) {
                Write-Warning "Could not unstack HWND $Hwnd; refusing to move the whole stack: $($unstack.Output)"
                return $false
            }

            $state = Wait-ForKomorebiWindowFocus `
                -Hwnd $Hwnd `
                -TimeoutMilliseconds $FocusTimeoutMilliseconds

            if ($null -eq $state) {
                Write-Warning "Lost focus on HWND $Hwnd after unstacking it."
                return $false
            }
        }

        for ($attempt = 1; $attempt -le 2; $attempt++) {
            $state = Wait-ForKomorebiWindowFocus `
                -Hwnd $Hwnd `
                -TimeoutMilliseconds $FocusTimeoutMilliseconds

            if ($null -eq $state) {
                continue
            }

            $locations = Get-WindowLocationMap -State $state
            if ($locations.ContainsKey($locationKey)) {
                $location = $locations[$locationKey]
                if ($location.MonitorIndex -eq $TargetMonitorIndex) {
                    $moved = $true
                    break
                }
            }

            $moveResult = Invoke-KomorebicCommand -Arguments @(
                "move-to-monitor",
                [string]$TargetMonitorIndex
            )

            if ($moveResult.ExitCode -ne 0) {
                Write-Verbose "move-to-monitor attempt $attempt failed: $($moveResult.Output)"
                Start-Sleep -Milliseconds 80
                continue
            }

            $verifyDeadline = [DateTime]::UtcNow.AddMilliseconds(
                $MoveVerificationTimeoutMilliseconds
            )

            do {
                $verifyState = Get-KomorebiState
                $verifyLocations = Get-WindowLocationMap -State $verifyState

                if ($verifyLocations.ContainsKey($locationKey)) {
                    $verifyLocation = $verifyLocations[$locationKey]
                    if ($verifyLocation.MonitorIndex -eq $TargetMonitorIndex) {
                        $moved = $true
                        break
                    }
                }

                Start-Sleep -Milliseconds 40
            }
            while ([DateTime]::UtcNow -lt $verifyDeadline)

            if ($moved) {
                break
            }
        }

        if (-not $moved) {
            Write-Warning "komorebi did not move HWND $Hwnd to monitor $TargetMonitorIndex."
            return $false
        }

        if ($restoreKomorebiMaximize) {
            $restoreMaximize = Invoke-KomorebicCommand -Arguments @("toggle-maximize")
            if ($restoreMaximize.ExitCode -ne 0) {
                Write-Verbose "The window moved, but maximized mode could not be restored: $($restoreMaximize.Output)"
            }
        }

        if ($restoreOriginMonocle) {
            $focusOrigin = Invoke-KomorebicCommand -Arguments @(
                "focus-monitor",
                [string]$originMonitorIndex
            )

            if ($focusOrigin.ExitCode -eq 0) {
                $restoreMonocle = Invoke-KomorebicCommand -Arguments @("toggle-monocle")
                if ($restoreMonocle.ExitCode -ne 0) {
                    Write-Verbose "The window moved, but monocle mode could not be restored on the origin monitor."
                }
            }

            [void](Invoke-KomorebicCommand -Arguments @(
                "focus-monitor",
                [string]$TargetMonitorIndex
            ))
        }

        Write-Verbose "Moved HWND $Hwnd from monitor $originMonitorIndex to monitor $TargetMonitorIndex."
        return $true
    }
    finally {
        Restore-PreviousForegroundWindow `
            -PreviousForegroundHwnd $PreviousForegroundHwnd `
            -MovedHwnd $Hwnd
    }
}

$command = Get-Command -Name $Komorebic -CommandType Application -ErrorAction Stop
$script:KomorebicPath = $command.Source
if ([string]::IsNullOrWhiteSpace($script:KomorebicPath)) {
    $script:KomorebicPath = $command.Path
}

$mutex = $null
$ownsMutex = $false
$pipe = $null
$pump = $null
$subscribed = $false
$pipeName = "komorebi_mouse_spawner_$PID"

try {
    $createdNew = $false
    $mutex = [System.Threading.Mutex]::new(
        $true,
        "Local\komorebi_mouse_spawner",
        [ref]$createdNew
    )

    if (-not $createdNew) {
        throw "Another instance of this subscriber is already running."
    }
    $ownsMutex = $true

    $pipe = [System.IO.Pipes.NamedPipeServerStream]::new(
        $pipeName,
        [System.IO.Pipes.PipeDirection]::In,
        1,
        [System.IO.Pipes.PipeTransmissionMode]::Byte,
        [System.IO.Pipes.PipeOptions]::Asynchronous,
        65536,
        65536
    )

    # The reader thread starts before subscribe-pipe. This is important because the
    # AddSubscriberPipe notification contains the entire komorebi state and can be
    # larger than the named-pipe buffer.
    $pump = [KomorebiMouseSpawner.PipeMessagePump]::new($pipe)
    $pump.Start()

    $subscribe = Invoke-KomorebicCommand -Arguments @("subscribe-pipe", $pipeName)
    if ($subscribe.ExitCode -ne 0) {
        throw "komorebic subscribe-pipe failed: $($subscribe.Output)"
    }
    $subscribed = $true

    if (-not $pump.Connected.Wait(5000)) {
        throw "komorebi did not connect to the named pipe within 5 seconds."
    }
    if ($null -ne $pump.Error) {
        throw $pump.Error
    }

    [KomorebiMouseSpawner.PipeMessage]$baselineMessage = $null
    if (-not $pump.Messages.TryTake([ref]$baselineMessage, 5000)) {
        if ($null -ne $pump.Error) {
            throw $pump.Error
        }
        throw "No initial notification was received from komorebi."
    }

    $baselineNotification = $baselineMessage.Line | ConvertFrom-Json -ErrorAction Stop
    $seenHwnds = [System.Collections.Generic.HashSet[System.Int64]]::new()
    $baselineLocations = Get-WindowLocationMap -State $baselineNotification.state

    foreach ($key in $baselineLocations.Keys) {
        [void]$seenHwnds.Add([Int64]$key)
    }

    Write-Verbose "Subscribed on pipe '$pipeName'; tracking $($seenHwnds.Count) existing windows."

    while ($true) {
        [KomorebiMouseSpawner.PipeMessage]$message = $null
        if (-not $pump.Messages.TryTake([ref]$message, 1000)) {
            if ($null -ne $pump.Error) {
                throw $pump.Error
            }

            if ($pump.Messages.IsCompleted) {
                break
            }

            continue
        }

        try {
            $notification = $message.Line | ConvertFrom-Json -ErrorAction Stop
        }
        catch {
            Write-Warning "Ignoring malformed komorebi notification: $($_.Exception.Message)"
            continue
        }

        $eventType = Get-NotificationEventType -Notification $notification
        $eventHwnd = Get-NotificationEventHwnd -Notification $notification

        if (($eventType -eq "Destroy" -or $eventType -eq "Unmanage") -and $null -ne $eventHwnd) {
            [void]$seenHwnds.Remove([Int64]$eventHwnd)
            continue
        }

        if ($eventType -notin @("Show", "Uncloak", "Manage") -or $null -eq $eventHwnd) {
            continue
        }

        $eventHwnd = [Int64]$eventHwnd
        if ($seenHwnds.Contains($eventHwnd)) {
            continue
        }

        $locations = Get-WindowLocationMap -State $notification.state
        $locationKey = [string]$eventHwnd
        if (-not $locations.ContainsKey($locationKey)) {
            # The event did not add a managed window (for example, a transient Show event).
            continue
        }

        # Mark it before moving so the focus/move notifications generated by this script
        # cannot cause a duplicate move.
        [void]$seenHwnds.Add($eventHwnd)

        $targetMonitorIndex = Get-MonitorIndexAtPoint `
            -State $notification.state `
            -X $message.CursorX `
            -Y $message.CursorY

        [void](Move-KomorebiWindowToMonitor `
            -Hwnd $eventHwnd `
            -TargetMonitorIndex $targetMonitorIndex `
            -NotificationState $notification.state `
            -PreviousForegroundHwnd $message.ForegroundHwnd)
    }
}
finally {
    if ($subscribed) {
        try {
            [void](Invoke-KomorebicCommand -Arguments @("unsubscribe-pipe", $pipeName))
        }
        catch {
            # Best-effort cleanup only.
        }
    }

    if ($null -ne $pump) {
        $pump.Dispose()
    }
    elseif ($null -ne $pipe) {
        $pipe.Dispose()
    }

    if ($ownsMutex -and $null -ne $mutex) {
        try { $mutex.ReleaseMutex() } catch { }
    }

    if ($null -ne $mutex) {
        $mutex.Dispose()
    }
}
